package com.imcys.bilibilias.core.ass

import com.imcys.bilibilias.core.ass.canvas.CanvasConfig
import com.imcys.bilibilias.core.ass.canvas.DrawEffect
import com.imcys.bilibilias.core.ass.canvas.Drawable
import java.io.BufferedWriter
import java.io.Closeable
import java.io.IOException
import java.io.Writer
import kotlin.time.Duration.Companion.seconds

// 假设之前的 DrawEffect, Drawable, CanvasConfig, Rgb 等类已定义
// data class Point(val x: Int, val y: Int)
// sealed class DrawEffect {
//     data class Move(val start: Point, val end: Point) : DrawEffect()
//     object Fixed : DrawEffect()
// }
// data class Danmu(val timelineS: Double, val content: String, val rgb: Rgb, ...)
// data class Drawable(val danmu: Danmu, val duration: Double, val styleName: String, val effect: DrawEffect)
// data class CanvasConfig(val font: String, val fontSize: Int, val opacity: Int, val bold: Boolean, val outline: Double, ...)

/**
 * 包装一个时间戳（秒），并提供 ASS 格式的字符串表示 (H:MM:SS.ss)。
 *
 * Kotlin 的 `toString()` 方法完美替代了 Rust 的 `fmt::Display` trait。
 */
data class TimePoint(val t: Double) {
    override fun toString(): String {
        return t.seconds.toComponents { hours, minutes, seconds, _ ->
            val hoursStr = hours.toString()
            val minutesStr = minutes.toString().padStart(2, '0')
            val secondsStr = seconds.toString().padStart(2, '0')
            "$hoursStr:$minutesStr:$secondsStr"
        }
    }
}

/**
 * 包装一个 DrawEffect，并提供 ASS 特效标签的字符串表示。
 *
 * 同样，使用 `toString()` 替代 `fmt::Display`。
 */
data class AssEffect(val effect: DrawEffect) {
    override fun toString(): String {
        return when (effect) {
            is DrawEffect.Move -> {
                val (x0, y0) = effect.start
                val (x1, y1) = effect.end
                "\\move($x0, $y0, $x1, $y1)"
            }

            is DrawEffect.Fixed -> {
//                logger.severe("Fixed danmaku should not appear here; they cannot be converted to ASS effects.")
                throw IllegalStateException("Cannot format a Fixed DrawEffect for ASS.")
            }
        }
    }
}

/**
 * 为 CanvasConfig 添加一个扩展函数，用于生成 ASS 格式的样式定义。
 *
 * 扩展函数是在 Kotlin 中为现有类添加新功能的最佳方式，
 * 完美对应 Rust 的 `impl CanvasConfig { ... }` 块。
 */
fun CanvasConfig.toAssStyles(): List<String> {
    // 将布尔值转换为 ASS 使用的 1 或 0
    val boldValue = if (this.bold) 1 else 0
    // ASS 的颜色格式是 AABBGGRR，而我们的 opacity (不透明度) 是 255-alpha
    // ASS 的 PrimaryColour alpha 是反的，&H00 是不透明，&HFF 是全透明
    val assAlpha = String.format("%02X", 255 - this.opacity)

    val baseStyle = """
        ${font},${fontSize},&H${assAlpha}FFFFFF,&H00FFFFFF,&H${assAlpha}000000,&H00000000,
        $boldValue,0,0,0,100,100,0.00,0.00,1,
        ${outline},0,7,0,0,0,1
    """.trim().replace("\n", "")

    return listOf(
        "Style: Float,$baseStyle",
        "Style: Bottom,$baseStyle",
        "Style: Top,$baseStyle"
    )
}

/**
 * 负责将 Drawable 对象写入任何 Writer，生成 ASS 字幕文件。
 *
 * @param W 泛型参数，代表任何实现了 java.io.Writer 的输出目标。
 * @property writer 目标 writer，内部使用 BufferedWriter 包装以提高性能。
 * @property title 字幕文件的标题。
 * @property canvasConfig 相关的画布配置。
 */
class AssWriter<W : Writer>(
    writer: W,
    private val title: String,
    private val canvasConfig: CanvasConfig
) : Closeable {

    // 使用 BufferedWriter 对应 Rust 的 BufWriter，并设置大容量缓存。
    // 10 shl 20 (10 << 20) in Rust is 10 * 2^20 = 10,485,760 bytes (10 MiB)
    private val bufferedWriter: BufferedWriter = BufferedWriter(writer, 10 * 1024 * 1024)

    init {
        // 在构造时直接写入文件头，对应 Rust 的 new() + init() 模式
        writeHeader()
    }

    private fun writeHeader() {
        // 使用多行字符串和字符串模板，代码非常清晰
        val styles = canvasConfig.toAssStyles().joinToString("\n")
        val header = """
            [Script Info]
            ; Script generated by danmu2ass
            Title: $title
            Script Updated By: danmu2ass (Kotlin version)
            ScriptType: v4.00+
            PlayResX: ${canvasConfig.width}
            PlayResY: ${canvasConfig.height}
            Aspect Ratio: ${canvasConfig.width}:${canvasConfig.height}
            Collisions: Normal
            WrapStyle: 2
            ScaledBorderAndShadow: yes
            YCbCr Matrix: TV.601


            [V4+ Styles]
            Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
            $styles

            [Events]
            Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
        """.trimIndent()

        bufferedWriter.write(header)
        bufferedWriter.newLine()
    }

    /**
     * 将一个 Drawable 对象写入为一行 ASS Dialogue。
     * @throws IOException 如果发生 I/O 错误。
     */
    @Throws(IOException::class)
    fun write(drawable: Drawable) {
        val start = TimePoint(drawable.danmu.timelineS)
        val end = TimePoint(drawable.danmu.timelineS + drawable.duration)
        val effect = AssEffect(drawable.effect)
        val (r, g, b) = drawable.danmu.rgb

        // ASS 颜色是 BGR 格式
        val colorTag = String.format("\\c&H%02X%02X%02X&", b, g, r)

        // ASS 特殊字符需要转义
        val text = escapeAssText(drawable.danmu.content)

        val dialogueLine =
            "Dialogue: 2,$start,$end,${drawable.styleName},,0,0,0,,{$effect$colorTag}$text"

        bufferedWriter.write(dialogueLine)
        bufferedWriter.newLine()
    }

    /**
     * 实现了 Closeable 接口，可以方便地使用 .use { ... } 语法来自动关闭 writer。
     */
    override fun close() {
        bufferedWriter.close()
    }

    private fun escapeAssText(text: String): String {
        // ASS 会将花括号内的内容作为标签解析，需要替换掉。
        // 同时，换行符需要用 \N 替换。
        return text.replace("{", "｛")
            .replace("}", "｝")
            .replace("\n", "\\N")
    }
}